"""
Scanner scoring and ranking -- pure computation, no I/O.

Combines the risk engine's output with regime alignment, momentum, and
liquidity into one composite score. This is intentionally a hand-tuned
weighted sum, not a learned model -- per the original build plan, a
meta-model here would be over-engineering before Module 6 (ML) exists
to validate whether it even helps.
"""

from dataclasses import dataclass, field

from trading_schemas import MarketRegime, RiskAssessment

WEIGHT_EXPECTED_VALUE = 0.40
WEIGHT_MOMENTUM = 0.25
WEIGHT_REGIME_ALIGNMENT = 0.20
WEIGHT_LIQUIDITY = 0.15


@dataclass
class ScoredCandidate:
    symbol: str
    composite_score: float
    risk_assessment: RiskAssessment
    momentum_score: float
    regime_alignment_score: float
    liquidity_score: float
    reasoning: list[str] = field(default_factory=list)


def compute_momentum_score(rsi_14: float) -> float:
    """Normalizes RSI (0-100) to roughly [-1, 1], centered on the neutral 50 line."""
    return max(-1.0, min(1.0, (rsi_14 - 50.0) / 50.0))


def compute_liquidity_score(volume_ratio: float) -> float:
    """volume_ratio: today's volume / 20-day average volume. 1.0 = normal.
    Rewards above-average volume (more reliable fills, real interest),
    penalizes thin volume, clipped to [-1, 1]."""
    return max(-1.0, min(1.0, volume_ratio - 1.0))


def compute_regime_alignment_score(regime: MarketRegime, regime_confidence: float) -> float:
    """
    Setups generated by generate_swing_setup are long-only, so a bullish
    regime supports them and a bearish regime works against them.
    High volatility is penalized regardless of direction -- per the
    problem statement, the regime engine should be able to reduce
    confidence or override strategy selection when conditions are
    unsuitable, independent of what any individual setup looks like.
    """
    if regime == MarketRegime.BULLISH:
        return regime_confidence
    if regime == MarketRegime.BEARISH:
        return -regime_confidence
    if regime == MarketRegime.HIGH_VOLATILITY:
        return -0.5
    return 0.0  # sideways, low_volatility, transitional: neutral


def compute_composite_score(
    risk_assessment: RiskAssessment,
    momentum_score: float,
    regime_alignment_score: float,
    liquidity_score: float,
) -> float:
    return (
        risk_assessment.expected_value_r * WEIGHT_EXPECTED_VALUE
        + momentum_score * WEIGHT_MOMENTUM
        + regime_alignment_score * WEIGHT_REGIME_ALIGNMENT
        + liquidity_score * WEIGHT_LIQUIDITY
    )


def build_reasoning(
    risk_assessment: RiskAssessment,
    momentum_score: float,
    regime: MarketRegime,
    regime_alignment_score: float,
    liquidity_score: float,
) -> list[str]:
    reasons = [
        f"Reward:risk {risk_assessment.reward_to_risk_ratio:.2f}, "
        f"expected value {risk_assessment.expected_value_r:+.2f}R",
        f"Risk category: {risk_assessment.risk_category.value}",
    ]
    if momentum_score > 0.2:
        reasons.append(f"Positive momentum (RSI-derived score {momentum_score:+.2f})")
    elif momentum_score < -0.2:
        reasons.append(f"Negative momentum (RSI-derived score {momentum_score:+.2f})")

    reasons.append(f"Market regime: {regime.value} (alignment score {regime_alignment_score:+.2f})")

    if liquidity_score > 0.2:
        reasons.append("Above-average volume")
    elif liquidity_score < -0.2:
        reasons.append("Below-average volume -- liquidity concern")

    if not risk_assessment.approved:
        reasons.append("REJECTED by risk engine: " + "; ".join(risk_assessment.rejection_reasons))

    return reasons


def rank_opportunities(candidates: list[ScoredCandidate], top_n: int = 5) -> list[ScoredCandidate]:
    """
    Only risk-engine-approved candidates are eligible -- the hard veto
    gate from Module 4 is enforced HERE, not just referenced. A
    disapproved trade never appears in the ranked output, regardless of
    how attractive its composite score looks.
    """
    approved = [c for c in candidates if c.risk_assessment.approved]
    ranked = sorted(approved, key=lambda c: c.composite_score, reverse=True)
    return ranked[:top_n]